repos:
  - repo: local
    hooks:
      - id: cmake-format
        name: cmake-format
        entry: cmake-format
        description: Format CMakeLists.txt files using cmake-format.
        args: ["--in-place"]
        language: python
        types: [cmake]

      - id: clang-format
        name: clang-format
        description: Format files with clang-format.
        entry: clang-format -i
        language: system
        files: ^(.+)\.(h|cpp)$
        args: ["-style=file"]
