name: macOS tests

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install requirements
        run: brew install ninja

      - name: Configure
        run: cmake -G Ninja -B build

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest
        working-directory: build

      - name: Benchmark
        run: ./benchmark_memory_pool
        working-directory: build/benchmark
